// sysroot/include/bits/syscall.h
#ifndef _BITS_SYSCALL_H
#define _BITS_SYSCALL_H

// ===================== HNX 原生系统调用 =====================
#define __NR_write          1   // SYS_WRITE
#define __NR_read           2   // SYS_READ
#define __NR_open           3   // SYS_OPEN
#define __NR_close          4   // SYS_CLOSE
#define __NR_lseek          5   // SYS_LSEEK
#define __NR_getpid         6   // SYS_GETPID
#define __NR_yield          7   // SYS_YIELD
#define __NR_exit           8   // SYS_EXIT
#define __NR_ipc_wait       9   // SYS_IPC_WAIT
#define __NR_ipc_wake       10  // SYS_IPC_WAKE
#define __NR_ep_create      11  // SYS_EP_CREATE
#define __NR_ep_send        12  // SYS_EP_SEND
#define __NR_ep_recv        13  // SYS_EP_RECV
#define __NR_io_setup       14
#define __NR_io_destroy     15
#define __NR_io_submit      16
#define __NR_io_cancel      17
#define __NR_io_getevents   18
#define __NR_setxattr       19
#define __NR_lsetxattr      20
#define __NR_fsetxattr      21
#define __NR_getxattr       22
#define __NR_lgetxattr      23
#define __NR_fgetxattr      24
#define __NR_listxattr      25
#define __NR_llistxattr     26
#define __NR_flistxattr     27
#define __NR_removexattr    28
#define __NR_lremovexattr   29
#define __NR_fremovexattr   30
#define __NR_getcwd         31
#define __NR_lookup_dcookie 32
#define __NR_eventfd2       33
#define __NR_epoll_create1  34
#define __NR_epoll_ctl      35
#define __NR_epoll_pwait    36
#define __NR_dup            37
#define __NR_dup3           38
#define __NR_fcntl          39
#define __NR_inotify_init1  40
#define __NR_inotify_add_watch 41
#define __NR_inotify_rm_watch 42
#define __NR_ioctl          43
#define __NR_ioprio_set     44
#define __NR_ioprio_get     45
#define __NR_flock          46
#define __NR_mknodat        47
#define __NR_mkdirat        48
#define __NR_unlinkat       49
#define __NR_symlinkat      50
#define __NR_linkat         51
#define __NR_renameat       52
#define __NR_umount2        53
#define __NR_mount          54
#define __NR_pivot_root     55
#define __NR_nfsservctl     56
#define __NR_statfs         57
#define __NR_fstatfs        58
#define __NR_truncate       59
#define __NR_ftruncate      60
#define __NR_fallocate      61
#define __NR_faccessat      62
#define __NR_chdir          63
#define __NR_fchdir         64
#define __NR_chroot         65
#define __NR_fchmod         66
#define __NR_fchmodat       67
#define __NR_fchownat       68
#define __NR_fchown         69
#define __NR_openat         70
#define __NR_vhangup        71
#define __NR_pipe2          72
#define __NR_quotactl       73
#define __NR_getdents64     74
#define __NR_readv          75
#define __NR_writev         76
#define __NR_pread64        77
#define __NR_pwrite64       78
#define __NR_preadv         79
#define __NR_pwritev        80
#define __NR_sendfile       81
#define __NR_pselect6       82
#define __NR_ppoll          83
#define __NR_signalfd4      84
#define __NR_vmsplice       85
#define __NR_splice         86
#define __NR_tee            87
#define __NR_readlinkat     88
#define __NR_newfstatat     89
#define __NR_fstat          90
#define __NR_sync           91
#define __NR_fsync          92
#define __NR_fdatasync      93
#define __NR_sync_file_range 94
#define __NR_timerfd_create 95
#define __NR_timerfd_settime 96
#define __NR_timerfd_gettime 97
#define __NR_utimensat      98
#define __NR_acct           99
#define __NR_capget         100
#define __NR_capset         101
#define __NR_personality    102
#define __NR_exit_group     103
#define __NR_waitid         104
#define __NR_set_tid_address 105
#define __NR_unshare        106
#define __NR_futex          107
#define __NR_set_robust_list 108
#define __NR_get_robust_list 109
#define __NR_nanosleep      110
#define __NR_getitimer      111
#define __NR_setitimer      112
#define __NR_kexec_load     113
#define __NR_init_module    114
#define __NR_delete_module  115
#define __NR_timer_create   116
#define __NR_timer_gettime  117
#define __NR_timer_getoverrun 118
#define __NR_timer_settime  119
#define __NR_timer_delete   120
#define __NR_clock_settime  121
#define __NR_clock_gettime  122
#define __NR_clock_getres   123
#define __NR_clock_nanosleep 124
#define __NR_syslog         125
#define __NR_ptrace         126
#define __NR_sched_setparam 127
#define __NR_sched_setscheduler 128
#define __NR_sched_getscheduler 129
#define __NR_sched_getparam 130
#define __NR_sched_setaffinity 131
#define __NR_sched_getaffinity 132
#define __NR_sched_yield    133
#define __NR_sched_get_priority_max 134
#define __NR_sched_get_priority_min 135
#define __NR_sched_rr_get_interval 136
#define __NR_restart_syscall 137
#define __NR_kill           138
#define __NR_tkill          139
#define __NR_tgkill         140
#define __NR_sigaltstack    141
#define __NR_rt_sigsuspend  142
#define __NR_rt_sigaction   143
#define __NR_rt_sigprocmask 144
#define __NR_rt_sigpending  145
#define __NR_rt_sigtimedwait 146
#define __NR_rt_sigqueueinfo 147
#define __NR_rt_sigreturn   148
#define __NR_setpriority    149
#define __NR_getpriority    150
#define __NR_reboot         151
#define __NR_setregid       152
#define __NR_setgid         153
#define __NR_setreuid       154
#define __NR_setuid         155
#define __NR_setresuid      156
#define __NR_getresuid      157
#define __NR_setresgid      158
#define __NR_getresgid      159
#define __NR_setfsuid       160
#define __NR_setfsgid       161
#define __NR_times          162
#define __NR_setpgid        163
#define __NR_getpgid        164
#define __NR_getsid         165
#define __NR_setsid         166
#define __NR_getgroups      167
#define __NR_setgroups      168
#define __NR_uname          169
#define __NR_sethostname    170
#define __NR_setdomainname  171
#define __NR_getrlimit      172
#define __NR_setrlimit      173
#define __NR_getrusage      174
#define __NR_umask          175
#define __NR_prctl          176
#define __NR_getcpu         177
#define __NR_gettimeofday   178
#define __NR_settimeofday   179
#define __NR_adjtimex       180
#define __NR_getppid        181
#define __NR_getuid         182
#define __NR_geteuid        183
#define __NR_getgid         184
#define __NR_getegid        185
#define __NR_gettid         186
#define __NR_sysinfo        187
#define __NR_mq_open        188
#define __NR_mq_unlink      189
#define __NR_mq_timedsend   190
#define __NR_mq_timedreceive 191
#define __NR_mq_notify      192
#define __NR_mq_getsetattr  193
#define __NR_msgget         194
#define __NR_msgctl         195
#define __NR_msgrcv         196
#define __NR_msgsnd         197
#define __NR_semget         198
#define __NR_semctl         199
#define __NR_semtimedop     200
#define __NR_semop          201
#define __NR_shmget         202
#define __NR_shmctl         203
#define __NR_shmat          204
#define __NR_shmdt          205
#define __NR_socket         206
#define __NR_socketpair     207
#define __NR_bind           208
#define __NR_listen         209
#define __NR_accept         210
#define __NR_connect        211
#define __NR_getsockname    212
#define __NR_getpeername    213
#define __NR_sendto         214
#define __NR_recvfrom       215
#define __NR_setsockopt     216
#define __NR_getsockopt     217
#define __NR_shutdown       218
#define __NR_sendmsg        219
#define __NR_recvmsg        220
#define __NR_readahead      221
#define __NR_brk            222
#define __NR_munmap         223
#define __NR_mremap         224
#define __NR_add_key        225
#define __NR_request_key    226
#define __NR_keyctl         227
#define __NR_clone          228
#define __NR_execve         229
#define __NR_mmap           230
#define __NR_fadvise64      231
#define __NR_swapon         232
#define __NR_swapoff        233
#define __NR_mprotect       234
#define __NR_msync          235
#define __NR_mlock          236
#define __NR_munlock        237
#define __NR_mlockall       238
#define __NR_munlockall     239
#define __NR_mincore        240
#define __NR_madvise        241
#define __NR_remap_file_pages 242
#define __NR_mbind          243
#define __NR_get_mempolicy  244
#define __NR_set_mempolicy  245
#define __NR_migrate_pages  246
#define __NR_move_pages     247
#define __NR_rt_tgsigqueueinfo 248
#define __NR_perf_event_open 249
#define __NR_accept4        250
#define __NR_recvmmsg       251
#define __NR_wait4          252
#define __NR_prlimit64      253
#define __NR_fanotify_init  254
#define __NR_fanotify_mark  255
#define __NR_name_to_handle_at 256
#define __NR_open_by_handle_at 257
#define __NR_clock_adjtime  258
#define __NR_syncfs         259
#define __NR_setns          260
#define __NR_sendmmsg       261
#define __NR_process_vm_readv 262
#define __NR_process_vm_writev 263
#define __NR_kcmp           264
#define __NR_finit_module   265
#define __NR_sched_setattr  266
#define __NR_sched_getattr  267
#define __NR_renameat2      268
#define __NR_seccomp        269
#define __NR_getrandom      270
#define __NR_memfd_create   271
#define __NR_bpf            272
#define __NR_execveat       273
#define __NR_userfaultfd    274
#define __NR_membarrier     275
#define __NR_mlock2         276
#define __NR_copy_file_range 277
#define __NR_preadv2        278
#define __NR_pwritev2       279
#define __NR_pkey_mprotect  280
#define __NR_pkey_alloc     281
#define __NR_pkey_free      282
#define __NR_statx          283
#define __NR_io_pgetevents  284
#define __NR_rseq           285
#define __NR_kexec_file_load 286
#define __NR_pidfd_send_signal 287
#define __NR_io_uring_setup 288
#define __NR_io_uring_enter 289
#define __NR_io_uring_register 290
#define __NR_open_tree      291
#define __NR_move_mount     292
#define __NR_fsopen         293
#define __NR_fsconfig       294
#define __NR_fsmount        295
#define __NR_fspick        296
#define __NR_pidfd_open     297
#define __NR_clone3         298
#define __NR_close_range    299
#define __NR_openat2        300
#define __NR_pidfd_getfd    301
#define __NR_faccessat2     302
#define __NR_process_madvise 303
#define __NR_epoll_pwait2   304
#define __NR_mount_setattr  305
#define __NR_landlock_create_ruleset 306
#define __NR_landlock_add_rule 307
#define __NR_landlock_restrict_self 308
#define __NR_process_mrelease 309
#define __NR_futex_waitv    310
#define __NR_set_mempolicy_home_node 311
#define __NR_cachestat      312
#define __NR_fchmodat2      313

#endif // _BITS_SYSCALL_H